services:
  db:
    image: postgres:14-bookworm
    volumes:
      - orig-pg-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: uipa
      POSTGRES_USER: uipa
      POSTGRES_PASSWORD: uipa
    ports:
      - "127.0.0.1:5432:5432"
  es:
    build:
      dockerfile: ./es.Dockerfile
    volumes:
      - orig-es-data:/usr/share/elasticsearch/data
      - orig-es-logs:/usr/share/elasticsearch/log
    ports:
      - "127.0.0.1:9200:9200"
  mailsink:
    image: fkantelberg/mail-devel:${MAILSINK_TAG:-latest}
    environment:
      MAIL_USER: ${MAILSINK_USER:-bogus@mailsink.dev}
    command: [--password, "${MAILSINK_PASSWORD:-secret}", --smtp-flagged-seen, --multi-user]
    ports:
      - "${MAILSINK_HTTP:-127.0.0.1:4080}:4080"
      - "${MAILSINK_SMTP:-127.0.0.1:4025}:4025"
      - "${MAILSINK_IMAP:-127.0.0.1:4143}:4143"

volumes:
  orig-es-data: {}
  orig-es-logs: {}
  orig-pg-data: {}
