[project]
name = "uipa"
version = "0.1.0"
description = "UIPA.org upgrade to current Python and Django"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "django~=4.2",
  "django-appconf",
  "Markdown",
  "importlib-metadata<5.0",
  "celery",
  "celery-haystack",
  "django-haystack",
  "django-celery-email",
  "django-taggit",
  "requests",
  "django-floppyforms~=1.8",
  "python-magic",
  "django-tastypie",
  "python-mimeparse>=0.1.4",
  "django-configurations",
  "django-storages==1.5.0",
  "dj-database-url==0.4.1",
  "django-cache-url==1.2.0",
  "django-compressor",
  "django-contrib-comments",
  "unicodecsv==0.14.1",
  "honcho==0.6.6",
  "python-docx",
  "elasticsearch==2.3.0",
  "psycopg2",
  "lxml",
  "boto==2.43.0",
  "setuptools==56.0.0",
  "gunicorn==23.0.0",
]

[dependency-groups]
dev = [
  "black == 24.*",
  "pytest-django",
  "factory-boy",
  "mock",
  "selenium",
 ]
