[project]
name = "uipa"
version = "0.1.0"
description = "UIPA.org upgrade to current Python and Django"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "django~=5.2",
  "django-appconf",
  "Markdown",
  "importlib-metadata",
  "celery",
  "celery-haystack",
  "django-haystack",
  "django-celery-email",
  "django-taggit",
  "requests",
  "django-floppyforms",
  "python-magic",
  "django-tastypie",
  "python-mimeparse",
  "django-configurations",
  "django-storages",
  "dj-database-url",
  "django-cache-url",
  "django-compressor",
  "django-contrib-comments",
  "unicodecsv",
  "honcho",
  "python-docx",
  "elasticsearch>=2.0.0,<3.0.0",
  "psycopg2",
  "lxml",
  "boto==2.43.0",
  "setuptools==56.0.0",
  "gunicorn",
]

[dependency-groups]
dev = [
  "black == 24.*",
  "pytest-django",
  "factory-boy",
  "mock",
  "selenium",
 ]
