# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-11 07:05


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foirequest', '0005_auto_20160902_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='foimessage',
            name='ccs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CCs'),
        ),
    ]
